version: '3'
services:
  ble_sensor_mqtt_gw:
    container_name: ble_sensor_mqtt_gw
    build:
      context: ./ble_sensor_mqtt_gw 
    restart: always
    network_mode: host
    privileged: true
    environment:
      BLE_DEVICE: 0
      SCAN_TIME: 7.0
      MQTT_HOST: '192.168.2.50'
      MQTT_PORT: 1883
      MQTT_TIMEOUT: 60
      MQTT_MAIN_TOPIC: 'sensors'
